#!/bin/bash

proj_name=$1

mkdir "$proj_name"

cd "$proj_name" || exit 1

mkdir src

touch src/Main.java

# Main.java mit Grundgerüst erzeugen
cat > src/Main.java <<EOF
public class Main {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}
EOF


cd ..

