# Wallpaper config for hyprpaper.
preload = ~/wallpaper.png
wallpaper = , ~/wallpaper.png

wallpaper {
    monitor = DP-1
    path = ~/wallpaper.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/wallpaper.png
    fit_mode = cover
}
