# Default two-monitor workspace layout. Override this in ~/.config/hypr-host.conf.
workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 5, monitor:DP-1
workspace = 6, monitor:DP-2
workspace = 7, monitor:DP-2
workspace = 8, monitor:DP-2
workspace = 9, monitor:DP-2
workspace = 10, monitor:DP-2

workspace = 1, on-created-empty:[state] $terminal
workspace = 8, on-created-empty:[state] firefox
